FROM python:3.12-slim

RUN pip install --no-cache-dir \
    dagster==1.13.3 \
    dagster-docker==0.29.3 \
    dagster-graphql==1.13.3 \
    dagster-postgres==0.29.3 \
    dagster-webserver==1.13.3

ENV DAGSTER_HOME=/opt/dagster/dagster_home
RUN mkdir -p "${DAGSTER_HOME}"

COPY deploy/dagster/dagster.yaml deploy/dagster/workspace.yaml "${DAGSTER_HOME}/"
WORKDIR "${DAGSTER_HOME}"
